"""initialize

Revision ID: abb9363cd21a
Revises: 
Create Date: 2023-06-20 15:29:35.690770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb9363cd21a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('global_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('project_url', sa.String(length=2048), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('commit', sa.String(length=40), nullable=False),
    sa.Column('language', sa.Enum('JAVA', 'CPP', 'JAVASCRIPT', 'PYTHON', 'RUBY', 'SWIFT', 'GO', 'CSHARP', name='snapshotlanguage'), nullable=False),
    sa.Column('state', sa.Enum('SNAPSHOT_FAILED', 'NOT_BUILT', 'BUILD_IN_PROGRESS', 'BUILD_FAILED', 'NOT_ANALYZED', 'ANALYSIS_FAILED', 'ANALYSIS_IN_PROGRESS', 'ANALYZED', name='snapshotstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_url', 'branch', 'commit', 'language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    # ### end Alembic commands ###
