"""Add snapshot labels

Revision ID: a68386d78f54
Revises: abb9363cd21a
Create Date: 2023-06-22 13:37:57.540520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68386d78f54'
down_revision = 'abb9363cd21a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_snapshots_global_id'), 'snapshots', ['global_id'])
    op.create_table('snapshot_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_labels'))
    )
    op.create_table('snapshot_label_association',
    sa.Column('snapshot_global_id', sa.String(), nullable=False),
    sa.Column('snapshot_label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_global_id'], ['snapshots.global_id'], name=op.f('fk_snapshot_label_association_snapshot_global_id_snapshots')),
    sa.ForeignKeyConstraint(['snapshot_label_id'], ['snapshot_labels.id'], name=op.f('fk_snapshot_label_association_snapshot_label_id_snapshot_labels')),
    sa.PrimaryKeyConstraint('snapshot_global_id', 'snapshot_label_id', name=op.f('pk_snapshot_label_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_snapshots_global_id'), 'snapshots', type_='unique')
    op.drop_table('snapshot_label_association')
    op.drop_table('snapshot_labels')
    # ### end Alembic commands ###
